# App
spring.application.name=email-campaign
server.port=${PORT:8080}

# SQLite + Hibernates
spring.datasource.url=jdbc:sqlite:/app/data/campaign.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Mail (use Gmail SMTP ? replace with your credentials)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Scheduler
spring.task.scheduling.pool.size=5

# Anthropic Claude API
anthropic.api.key=${ANTHROPIC_API_KEY}