name: Trigger Render Job

on:
  workflow_dispatch:

jobs:
  trigger-job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Job
        run: |
          curl -X POST "${{secrets.RENDER_JOB_HOOK}}"
